kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-codegen-matrix-custom-nov6-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: test-codegen-matrix-custom-nov6-dsp-job
    namespace: rhdh-custom-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-codegen-matrix-custom-nov6-imagestream-job-role
